<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Bandeja',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-mail',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2023-08-17 14:32:34',
                'route' => 'bandeja.index',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2021-06-02 10:07:22',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => 11,
                'order' => 1,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2023-08-18 05:39:03',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => 11,
                'order' => 2,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2021-06-02 10:08:05',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 14,
                'created_at' => '2021-06-02 13:55:32',
                'updated_at' => '2024-10-08 12:29:58',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2021-06-02 10:07:22',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2021-06-02 10:07:22',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2021-06-02 10:07:22',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2021-06-02 10:07:23',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2021-06-02 13:55:33',
                'updated_at' => '2024-10-08 12:29:58',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 11,
                'menu_id' => 1,
                'title' => 'Seguridad',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2021-06-02 10:07:53',
                'updated_at' => '2024-10-08 12:29:58',
                'route' => NULL,
                'parameters' => '',
            ),
            11 => 
            array (
                'id' => 12,
                'menu_id' => 1,
                'title' => 'Limpiar cache',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-refresh',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 15,
                'created_at' => '2021-06-25 14:03:59',
                'updated_at' => '2026-06-08 19:31:56',
                'route' => 'clear.cache',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'menu_id' => 1,
                'title' => 'Entidades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 4,
                'created_at' => '2021-07-09 12:17:41',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'voyager.entities.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Parámetros',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-params',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2021-07-09 12:18:42',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => NULL,
                'parameters' => '',
            ),
            14 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Acciones',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paperclip',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 5,
                'created_at' => '2021-07-09 12:36:52',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'voyager.acctions.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Departamentos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-milestone',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 6,
                'created_at' => '2021-07-09 12:40:34',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'voyager.departamentos.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'menu_id' => 1,
                'title' => 'Estados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list-add',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 7,
                'created_at' => '2021-07-09 12:53:03',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'voyager.estados.index',
                'parameters' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Tipos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tag',
                'color' => NULL,
                'parent_id' => 14,
                'order' => 8,
                'created_at' => '2021-07-09 13:11:58',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'voyager.tipos.index',
                'parameters' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Ingresos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2021-07-10 13:26:25',
                'updated_at' => '2023-08-17 14:32:34',
                'route' => 'entradas.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Certificados',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-receipt',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2021-07-16 04:30:24',
                'updated_at' => '2023-08-18 05:23:09',
                'route' => 'list.certificates',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Categorias',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-chat',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 3,
                'created_at' => '2021-09-07 12:20:45',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'voyager.categories.index',
                'parameters' => 'null',
            ),
            21 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Ingresos a RDE',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-credit-cards',
                'color' => '#000000',
                'parent_id' => 35,
                'order' => 1,
                'created_at' => '2022-05-18 07:48:54',
                'updated_at' => '2023-08-18 10:59:56',
                'route' => 'report.rde.index',
                'parameters' => 'null',
            ),
            22 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Persona Externas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 1,
                'created_at' => '2022-05-18 08:02:12',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'people_exts.index',
                'parameters' => NULL,
            ),
            23 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Cargos Adicionales',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-puzzle',
                'color' => '#000000',
                'parent_id' => 14,
                'order' => 2,
                'created_at' => '2022-05-18 08:03:44',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'additional_jobs.index',
                'parameters' => NULL,
            ),
            24 => 
            array (
                'id' => 26,
                'menu_id' => 1,
                'title' => 'Reporte Entrada/Despachada',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-receipt',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 1,
                'created_at' => '2022-06-07 04:54:35',
                'updated_at' => '2022-06-07 08:28:59',
                'route' => 'view.list-document',
                'parameters' => 'null',
            ),
            25 => 
            array (
                'id' => 30,
                'menu_id' => 1,
                'title' => 'Intercambio Bandeja',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-people-arrows',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2022-08-05 05:11:17',
                'updated_at' => '2023-08-18 12:52:16',
                'route' => 'exchange.index',
                'parameters' => 'null',
            ),
            26 => 
            array (
                'id' => 31,
                'menu_id' => 1,
                'title' => 'Ordenes de Embargo',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-square-pen',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2022-10-03 08:18:45',
                'updated_at' => '2023-08-18 10:39:14',
                'route' => 'voyager.embargos.index',
                'parameters' => 'null',
            ),
            27 => 
            array (
                'id' => 33,
                'menu_id' => 1,
                'title' => 'Reporte Ingresos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 2,
                'created_at' => '2023-03-01 11:03:09',
                'updated_at' => '2023-03-02 04:58:28',
                'route' => 'view.report.ingreso',
                'parameters' => 'null',
            ),
            28 => 
            array (
                'id' => 34,
                'menu_id' => 1,
                'title' => 'Reporte Bandeja',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => 27,
                'order' => 3,
                'created_at' => '2023-03-02 04:58:15',
                'updated_at' => '2023-03-02 04:58:44',
                'route' => 'view.report.bandeja',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => 35,
                'menu_id' => 1,
                'title' => 'Reportes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'fa-solid fa-print',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2023-07-11 07:31:00',
                'updated_at' => '2024-10-08 12:29:58',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => 36,
                'menu_id' => 1,
                'title' => 'Documentos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => 35,
                'order' => 2,
                'created_at' => '2023-07-11 07:35:20',
                'updated_at' => '2023-08-18 11:35:48',
                'route' => 'report.rde.documents.index',
                'parameters' => 'null',
            ),
            31 => 
            array (
                'id' => 37,
                'menu_id' => 1,
                'title' => 'Inicio',
                'url' => 'admin',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2023-08-17 14:32:26',
                'updated_at' => '2023-08-17 14:32:34',
                'route' => NULL,
                'parameters' => '',
            ),
            32 => 
            array (
                'id' => 41,
                'menu_id' => 1,
                'title' => 'Directorio Telefonico',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-telephone',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2024-10-03 06:19:23',
                'updated_at' => '2024-10-04 11:43:14',
                'route' => 'directorio-telefonico.index',
                'parameters' => 'null',
            ),
            33 => 
            array (
                'id' => 42,
                'menu_id' => 1,
                'title' => 'Directorio Grupos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-play',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2024-10-08 12:10:30',
                'updated_at' => '2024-10-08 12:32:51',
                'route' => 'voyager.directorio-grupos.index',
                'parameters' => 'null',
            ),
        ));
        
        
    }
}