<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-mail',
                'id' => 1,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'bandeja.index',
                'target' => '_self',
                'title' => 'Bandeja',
                'updated_at' => '2023-08-17 18:32:34',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            2 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 11,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Usuarios',
                'updated_at' => '2023-08-18 09:39:03',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 11,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2021-06-02 14:08:05',
                'url' => '',
            ),
            4 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 17:55:32',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 14,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Herramientas',
                'updated_at' => '2024-10-08 16:29:58',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2021-06-02 14:07:22',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2021-06-02 14:07:23',
                'url' => '',
            ),
            9 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 17:55:33',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 13,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Configuración',
                'updated_at' => '2024-10-08 16:29:58',
                'url' => '',
            ),
            10 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-02 14:07:53',
                'icon_class' => 'voyager-lock',
                'id' => 11,
                'menu_id' => 1,
                'order' => 12,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Seguridad',
                'updated_at' => '2024-10-08 16:29:58',
                'url' => '',
            ),
            11 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-06-25 18:03:59',
                'icon_class' => 'voyager-refresh',
                'id' => 12,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'clear.cache',
                'target' => '_self',
                'title' => 'Limpiar cache',
                'updated_at' => '2022-10-26 15:04:27',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2021-07-09 16:17:41',
                'icon_class' => 'voyager-company',
                'id' => 13,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 14,
                'route' => 'voyager.entities.index',
                'target' => '_self',
                'title' => 'Entidades',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            13 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-07-09 16:18:42',
                'icon_class' => 'voyager-params',
                'id' => 14,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Parámetros',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            14 => 
            array (
                'color' => NULL,
                'created_at' => '2021-07-09 16:36:52',
                'icon_class' => 'voyager-paperclip',
                'id' => 15,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 14,
                'route' => 'voyager.acctions.index',
                'target' => '_self',
                'title' => 'Acciones',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            15 => 
            array (
                'color' => NULL,
                'created_at' => '2021-07-09 16:40:34',
                'icon_class' => 'voyager-milestone',
                'id' => 16,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 14,
                'route' => 'voyager.departamentos.index',
                'target' => '_self',
                'title' => 'Departamentos',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            16 => 
            array (
                'color' => NULL,
                'created_at' => '2021-07-09 16:53:03',
                'icon_class' => 'voyager-list-add',
                'id' => 17,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => 14,
                'route' => 'voyager.estados.index',
                'target' => '_self',
                'title' => 'Estados',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            17 => 
            array (
                'color' => NULL,
                'created_at' => '2021-07-09 17:11:58',
                'icon_class' => 'voyager-tag',
                'id' => 18,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => NULL,
                'parent_id' => 14,
                'route' => 'voyager.tipos.index',
                'target' => '_self',
                'title' => 'Tipos',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            18 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-07-10 17:26:25',
                'icon_class' => 'voyager-credit-cards',
                'id' => 19,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'entradas.index',
                'target' => '_self',
                'title' => 'Ingresos',
                'updated_at' => '2023-08-17 18:32:34',
                'url' => '',
            ),
            19 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-07-16 08:30:24',
                'icon_class' => 'voyager-receipt',
                'id' => 20,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'list.certificates',
                'target' => '_self',
                'title' => 'Certificados',
                'updated_at' => '2023-08-18 09:23:09',
                'url' => '',
            ),
            20 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-09-07 16:20:45',
                'icon_class' => 'voyager-chat',
                'id' => 21,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => 'null',
                'parent_id' => 14,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categorias',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            21 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-05-18 11:48:54',
                'icon_class' => 'voyager-credit-cards',
                'id' => 23,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 35,
                'route' => 'report.rde.index',
                'target' => '_self',
                'title' => 'Ingresos a RDE',
                'updated_at' => '2023-08-18 14:59:56',
                'url' => '',
            ),
            22 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-05-18 12:02:12',
                'icon_class' => 'voyager-people',
                'id' => 24,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 14,
                'route' => 'people_exts.index',
                'target' => '_self',
                'title' => 'Persona Externas',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            23 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-05-18 12:03:44',
                'icon_class' => 'voyager-puzzle',
                'id' => 25,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 14,
                'route' => 'additional_jobs.index',
                'target' => '_self',
                'title' => 'Cargos Adicionales',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            24 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-06-07 08:54:35',
                'icon_class' => 'voyager-receipt',
                'id' => 26,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 27,
                'route' => 'view.list-document',
                'target' => '_self',
                'title' => 'Reporte Entrada/Despachada',
                'updated_at' => '2022-06-07 12:28:59',
                'url' => '',
            ),
            25 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-08-05 09:11:17',
                'icon_class' => 'fa-solid fa-people-arrows',
                'id' => 30,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'exchange.index',
                'target' => '_self',
                'title' => 'Intercambio Bandeja',
                'updated_at' => '2023-08-18 16:52:16',
                'url' => '',
            ),
            26 => 
            array (
                'color' => '#000000',
                'created_at' => '2022-10-03 12:18:45',
                'icon_class' => 'fa-solid fa-square-pen',
                'id' => 31,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.embargos.index',
                'target' => '_self',
                'title' => 'Ordenes de Embargo',
                'updated_at' => '2023-08-18 14:39:14',
                'url' => '',
            ),
            27 => 
            array (
                'color' => NULL,
                'created_at' => '2023-01-12 15:56:07',
                'icon_class' => 'fa-solid fa-file',
                'id' => 32,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.enlaces.index',
                'target' => '_self',
                'title' => 'Enlaces',
                'updated_at' => '2023-08-18 09:23:01',
                'url' => '',
            ),
            28 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-03-01 15:03:09',
                'icon_class' => 'fa-solid fa-print',
                'id' => 33,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 27,
                'route' => 'view.report.ingreso',
                'target' => '_self',
                'title' => 'Reporte Ingresos',
                'updated_at' => '2023-03-02 08:58:28',
                'url' => '',
            ),
            29 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-03-02 08:58:15',
                'icon_class' => 'fa-solid fa-print',
                'id' => 34,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 27,
                'route' => 'view.report.bandeja',
                'target' => '_self',
                'title' => 'Reporte Bandeja',
                'updated_at' => '2023-03-02 08:58:44',
                'url' => '',
            ),
            30 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-07-11 11:31:00',
                'icon_class' => 'fa-solid fa-print',
                'id' => 35,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Reportes',
                'updated_at' => '2024-10-08 16:29:58',
                'url' => '',
            ),
            31 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-07-11 11:35:20',
                'icon_class' => 'voyager-news',
                'id' => 36,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 35,
                'route' => 'report.rde.documents.index',
                'target' => '_self',
                'title' => 'Documentos',
                'updated_at' => '2023-08-18 15:35:48',
                'url' => '',
            ),
            32 => 
            array (
                'color' => '#000000',
                'created_at' => '2023-08-17 18:32:26',
                'icon_class' => 'voyager-home',
                'id' => 37,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Inicio',
                'updated_at' => '2023-08-17 18:32:34',
                'url' => 'admin',
            ),
            33 => 
            array (
                'color' => '#000000',
                'created_at' => '2024-10-03 10:19:23',
                'icon_class' => 'voyager-telephone',
                'id' => 41,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'directorio-telefonico.index',
                'target' => '_self',
                'title' => 'Directorio Telefonico',
                'updated_at' => '2024-10-04 15:43:14',
                'url' => '',
            ),
            34 => 
            array (
                'color' => '#000000',
                'created_at' => '2024-10-08 16:10:30',
                'icon_class' => 'voyager-play',
                'id' => 42,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.directorio-grupos.index',
                'target' => '_self',
                'title' => 'Directorio Grupos',
                'updated_at' => '2024-10-08 16:32:51',
                'url' => '',
            ),
        ));
        
        
    }
}